# TODO: delete this file after the RP manager key migration completes.
query FetchAdminRpManagerKeyAudit($rpId: String!) {
  rp_registration_by_pk(rp_id: $rpId) {
    is_unique_manager_key
  }
  rp_manager_key_migration_audit_by_pk(rp_id: $rpId) {
    rp_id
    app_id
    old_manager_kms_key_id
    old_manager_kms_key_arn
    shared_manager_kms_key_id
    cleanup_status
    last_error_detail
    deletion_scheduled_at
    expected_deletion_at
    created_at
    updated_at
  }
}
