query FetchOIDCApp($app_id: String!, $redirect_uri: String!) {
  app(
    where: {
      id: { _eq: $app_id }
      status: { _eq: "active" }
      is_archived: { _eq: false }
      engine: { _eq: "cloud" }
    }
  ) {
    id
    is_staging
    actions(where: { action: { _eq: "" } }) {
      id
      external_nullifier
      status
      redirects(where: { redirect_uri: { _eq: $redirect_uri } }) {
        redirect_uri
      }
    }
  }
}
