"use client";

import { ApolloLink, HttpLink } from "@apollo/client";
import {
  ApolloClient,
  ApolloNextAppProvider,
  InMemoryCache,
  SSRMultipartLink,
} from "@apollo/client-integration-nextjs";

function makeClient() {
  const httpLink = new HttpLink({
    uri: `/api/v1/graphql`,
  });

  return new ApolloClient({
    cache: new InMemoryCache(),
    link:
      typeof window === "undefined"
        ? ApolloLink.from([
            new SSRMultipartLink({
              stripDefer: true,
            }),
            httpLink,
          ])
        : httpLink,
  });
}

export function ApolloWrapper({
  nonce,
  children,
}: React.PropsWithChildren<{ nonce?: string }>) {
  return (
    <ApolloNextAppProvider
      makeClient={makeClient}
      // Apollo's SSR-rehydration transport injects an inline <script>. Pass
      // the CSP nonce generated by middleware (`x-nonce`) so the browser
      // doesn't block that script under our strict script-src.
      extraScriptProps={nonce ? { nonce } : undefined}
    >
      {children}
    </ApolloNextAppProvider>
  );
}
