"use client";

import { ApolloLink, HttpLink } from "@apollo/client";
import {
  ApolloNextAppProvider,
  NextSSRApolloClient,
  NextSSRInMemoryCache,
  SSRMultipartLink,
} from "@apollo/experimental-nextjs-app-support/ssr";

function makeClient() {
  const httpLink = new HttpLink({
    uri: `/api/v1/graphql`,
  });

  return new NextSSRApolloClient({
    cache: new NextSSRInMemoryCache(),
    link:
      typeof window === "undefined"
        ? (ApolloLink.from([
            new SSRMultipartLink({
              stripDefer: true,
            }) as any,
            httpLink,
          ]) as any)
        : httpLink,
  });
}

export function ApolloWrapper({
  nonce,
  children,
}: React.PropsWithChildren<{ nonce?: string }>) {
  return (
    <ApolloNextAppProvider
      makeClient={makeClient}
      // Apollo's SSR-rehydration transport injects an inline <script>. Pass
      // the CSP nonce generated by middleware (`x-nonce`) so the browser
      // doesn't block that script under our strict script-src.
      extraScriptProps={nonce ? { nonce } : undefined}
    >
      {children}
    </ApolloNextAppProvider>
  );
}
