export const REVIEWER_DEVELOPER_MESSAGE_MAX_LENGTH = 20_000;
export const REVIEWER_OVERRIDE_REASON_MAX_LENGTH = 10_000;
export const REVIEWER_CHECKLIST_EVIDENCE_MAX_LENGTH = 10_000;
export const REVIEWER_APPLICABILITY_NOTE_MAX_LENGTH = 5_000;
export const REVIEWER_INTERNAL_NOTES_MAX_LENGTH = 20_000;
