version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    reviewers:
      - "andy-t-wang"
      - "michalstruck"
    assignees:
      - "andy-t-wang"
      - "michalstruck"
