query FetchTeamMembers(
  $teamId: String!
  $invitesCondition: [invite_bool_exp!]
  $membersCondition: [membership_bool_exp!]
) {
  invites: invite(
    where: {
      team_id: { _eq: $teamId }
      expires_at: { _gte: "now()" }
      _or: $invitesCondition
    }
  ) {
    id
    email
    expires_at
  }
  members: membership(
    where: { team_id: { _eq: $teamId }, _or: $membersCondition }
  ) {
    id
    role
    user {
      name
      email
      id
      world_id_nullifier
    }
  }
}
