mutation verifyApp(
  $app_id: String!
  $id_to_verify: String!
  $operation_id: uuid!
  $expected_metadata_updated_at: timestamptz!
  $expected_prior_verified_id: String
  $expected_prior_verified_updated_at: timestamptz
  $expected_localization_versions: jsonb!
  $reviewer_name: String!
  $is_reviewer_app_store_approved: Boolean!
  $is_reviewer_world_app_approved: Boolean!
  $metadata_assets: jsonb!
  $localization_assets: jsonb!
) {
  legacy_verify_app_metadata(
    args: {
      p_app_id: $app_id
      p_app_metadata_id: $id_to_verify
      p_operation_id: $operation_id
      p_expected_metadata_updated_at: $expected_metadata_updated_at
      p_expected_prior_verified_id: $expected_prior_verified_id
      p_expected_prior_verified_updated_at: $expected_prior_verified_updated_at
      p_expected_localization_versions: $expected_localization_versions
      p_reviewer_name: $reviewer_name
      p_is_reviewer_app_store_approved: $is_reviewer_app_store_approved
      p_is_reviewer_world_app_approved: $is_reviewer_world_app_approved
      p_metadata_assets: $metadata_assets
      p_localization_assets: $localization_assets
    }
  ) {
    id
  }
}
