fragment GetLatestLayoutApp on layout_app {
  __typename
  location_index
  app {
    app_metadata {
      name
      short_name
      app_id
      logo_img_url
      showcase_img_urls
      hero_image_url
      world_app_description
      world_app_button_text
      whitelisted_addresses
      app_mode
      description
      category
      integration_url
      app_website_url
      source_code_url
      support_link
      supported_countries
      supported_languages
      associated_domains
      contracts
      permit2_tokens
      can_import_all_contacts
      is_reviewer_world_app_approved
      verification_status
      localisations(where: { locale: { _eq: $locale } }) {
        name
        world_app_button_text
        world_app_description
        short_name
        description
      }
    }
    name
  }
}

fragment GetLatestLayoutBanner on layout_banner {
  __typename
  location_index
  title
  title_color_hex
  subtitle
  subtitle_color_hex
  highlight_color_hex
  background_color_hex
  background_image_url
}

query GetLatestLayout($locale: String!) {
  layout(order_by: { created_at: desc }, limit: 1) {
    id
    layout_categories {
      __typename
      location_index
      category
      layout_apps {
        location_index
        ...GetLatestLayoutApp
      }
      layout_banners {
        __typename
        ...GetLatestLayoutBanner
      }
      layout_app_collections {
        __typename
        location_index
        indexed
        title
        layout_apps {
          ...GetLatestLayoutApp
        }
      }
      layout_banner_collections {
        __typename
        location_index
        title
        layout_banners {
          ...GetLatestLayoutBanner
        }
      }
      layout_secondary_categories {
        __typename
        location_index
        title
        subtitle
        background_color_hex
        background_image_url
        layout_apps {
          ...GetLatestLayoutApp
        }
        layout_banners {
          ...GetLatestLayoutBanner
        }
        layout_app_collections {
          __typename
          location_index
          indexed
          title
          layout_apps {
            ...GetLatestLayoutApp
          }
        }
        layout_banner_collections {
          __typename
          location_index
          title
          layout_banners {
            ...GetLatestLayoutBanner
          }
        }
      }
    }
  }
}
