DELETE FROM "public"."nullifier";
DELETE FROM "public"."auth_code";
DELETE FROM "public"."revocation";
DELETE FROM "public"."action";
DELETE FROM "public"."app";
DELETE FROM "public"."user";
DELETE FROM "public"."team";
DELETE FROM "public"."jwks";
DELETE FROM "public"."cache";