query GetVerificationData($id: String!) {
  verificationStatus: app_by_pk(id: $id) {
    app_metadata {
      verification_status
    }
  }

  verificationData: app_by_pk(id: $id) {
    app_metadata(
      where: {
        _or: [
          { verification_status: { _eq: "changes_requested" } }
          { verification_status: { _eq: "verified" } }
        ]
      }
    ) {
      id
      review_message
      verification_status
    }
  }
}
