-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."app_metadata" add column "short_name" varchar
--  not null default '""';
