query FetchApps($teamId: String!) {
  app(where: { team_id: { _eq: $teamId } }) {
    id
    is_staging
    engine
    app_metadata {
      id
      name
      logo_img_url
      verification_status
    }
  }
}
