query FetchAppStats(
  $appId: String!
  $startsAt: timestamptz!
  $timeSpan: String!
) {
  app_stats(args: { appId: $appId, startsAt: $startsAt, timespan: $timeSpan }) {
    app_id
    date
    verifications
    unique_users
  }
  app_stats_aggregate(
    args: { appId: $appId, startsAt: $startsAt, timespan: $timeSpan }
  ) {
    aggregate {
      sum {
        verifications
        unique_users
      }
    }
  }
  app(where: { id: { _eq: $appId } }) {
    id
    engine
  }
}
