-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."action" add column "client_secret" varchar
--  not null default '''';
