-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user" add column "posthog_id" varchar
--  null unique default gen_random_friendly_id('posthog_id'::character varying);
