query GetVerificationData($id: String!) {
  app: app_by_pk(id: $id) {
    id
    app_metadata(
      where: {
        _or: [
          { verification_status: { _eq: "changes_requested" } }
          { verification_status: { _eq: "verified" } }
        ]
      }
    ) {
      id
      review_message
      verification_status
    }
  }
}
