mutation InsertMembership(
  $team_id: String!
  $user_id: String
  $role: role_enum
  $invite_id: String!
) {
  insert_membership_one(
    object: { team_id: $team_id, user_id: $user_id, role: $role }
  ) {
    user {
      id
      email
      name
      auth0Id
      posthog_id
      name
      memberships {
        team {
          id
          name
        }
        role
      }
    }
    team_id
    role
  }

  delete_invite_by_pk(id: $invite_id) {
    id
  }
}
