query FetchAppSecret($app_id: String!) {
  app(
    where: {
      id: { _eq: $app_id }
      status: { _eq: "active" }
      is_archived: { _eq: false }
      engine: { _eq: "cloud" }
    }
  ) {
    id
    actions(limit: 1, where: { action: { _eq: "" } }) {
      client_secret
    }
  }
}
