mutation InsertAuthCode(
  $auth_code: String!
  $code_challenge: String
  $code_challenge_method: String
  $expires_at: timestamptz!
  $nullifier_hash: String!
  $app_id: String!
  $verification_level: String!
  $scope: jsonb!
  $nonce: String
  $redirect_uri: String
) {
  insert_auth_code_one(
    object: {
      auth_code: $auth_code
      code_challenge: $code_challenge
      code_challenge_method: $code_challenge_method
      expires_at: $expires_at
      nullifier_hash: $nullifier_hash
      app_id: $app_id
      verification_level: $verification_level
      scope: $scope
      nonce: $nonce
      redirect_uri: $redirect_uri
    }
  ) {
    auth_code
    nonce
  }
}
