mutation InsertJWK(
  $expires_at: timestamptz!
  $public_jwk: jsonb!
  $kms_id: String!
) {
  insert_jwks_one(
    object: {
      expires_at: $expires_at
      kms_id: $kms_id
      public_jwk: $public_jwk
    }
  ) {
    id
    kms_id
    expires_at
  }
}
