query FetchAdminTeams(
  $includeActiveApiKeysCount: Boolean!
  $includeAppsCount: Boolean!
  $includeCreatedAt: Boolean!
  $includeMembersCount: Boolean!
  $includePendingInvitesCount: Boolean!
  $includeStatus: Boolean!
  $limit: Int!
  $offset: Int!
  $orderBy: [team_order_by!]!
  $where: team_bool_exp!
) {
  team(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    name
    created_at @include(if: $includeCreatedAt)
    deleted_at @include(if: $includeStatus)
  }
  team_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  membership @include(if: $includeMembersCount) {
    team_id
  }
  app(
    where: { deleted_at: { _is_null: true } }
  ) @include(if: $includeAppsCount) {
    team_id
  }
  api_key(
    where: { is_active: { _eq: true } }
  ) @include(if: $includeActiveApiKeysCount) {
    team_id
  }
  invite(
    where: { expires_at: { _gte: "now()" } }
  ) @include(if: $includePendingInvitesCount) {
    team_id
  }
}
