query FetchAdminTeams($limit: Int!, $offset: Int!) {
  team(limit: $limit, offset: $offset, order_by: { created_at: desc }) {
    id
    name
    created_at
    deleted_at
  }
  team_aggregate {
    aggregate {
      count
    }
  }
  membership {
    team_id
  }
  app(where: { deleted_at: { _is_null: true } }) {
    team_id
  }
  api_key(where: { is_active: { _eq: true } }) {
    team_id
  }
  invite(where: { expires_at: { _gte: "now()" } }) {
    team_id
  }
}
