mutation RemoveUser(
  $userId: String!
  $teamId: String!
  $currentUserId: String!
) {
  delete_membership(
    where: {
      _and: [
        { user_id: { _eq: $userId } }
        { user_id: { _neq: $currentUserId } }
        { team_id: { _eq: $teamId } }
      ]
    }
  ) {
    affected_rows
  }
}
