name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy stacks
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OIDC Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::033662022620:role/oidc/cdk-cicd-worldid-stage
          role-session-name: worldid-dev-portal-staging-oidc-session
          aws-region: us-east-1
          mask-aws-account-id: false
          role-skip-session-tagging: true
      - name: Install node modules
        run: yarn install
        working-directory: infrastructure
      - name: Install CDK globally
        run: yarn global add aws-cdk
      - name: Deploy CDK stacks
        run: cdk deploy --all --context stage=staging --require-approval never
        working-directory: infrastructure
      - name: Install Hasura CLI
        run: |
          yarn global add hasura-cli@2.12.0
      - name: Apply DB migrations
        run: |
          cd hasura
          hasura migrate apply --endpoint=https://api.staging.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}' --all-databases
          hasura metadata apply --endpoint=https://api.staging.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
          hasura metadata reload --endpoint=https://api.staging.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
