name: Relyance SCI Scan

on:
  #TODO: Modify the cron job schedule below.
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  #TODO: Modify the job names and the machine below if you would like.
  execute-relyance-sci:
    name: Relyance SCI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # TODO: Update the docker pull command in the "run" section below. Recommend setting the ACCESS_TOKEN as an environment variable.
      - name: Pull and run SCI binary
        run: |-
          docker pull gcr.io/relyance-ext/compliance_inspector:release && \
          docker run --rm -v `pwd`:/repo --env 'API_KEY=tfh:18f345499cd9a7ecb24aa7b9e1f8f39b' gcr.io/relyance-ext/compliance_inspector:release
