name: Dispatch event

on:
  push:
    branches:
      - dev
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          repository: worldcoin/developer-portal-deployment
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}"}'
